CREATE DATABASE IF NOT EXISTS test5;
USE test5;
CREATE TABLE IF NOT EXISTS test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data VARCHAR(255) NOT NULL
);

CREATE DATABASE IF NOT EXISTS test6;
USE test6; -- <- database being used
CREATE TABLE IF NOT EXISTS test_table6 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

